plugins {
    id("buildlogic.kotlin")
    id("buildlogic.kotlinx-serialization-json")
    application
}

application {
    mainClass = "app.MainKt"
}

val generatedDir = rootDir.resolve("docs/pages/generated")

val cleanGenerated by tasks.registering(Delete::class) {
    delete(generatedDir)
}

tasks.named<JavaExec>("run") {
    dependsOn(cleanGenerated)
    outputs.dir(generatedDir)
}

tasks.clean {
    dependsOn(cleanGenerated)
}
